# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'example' do
    pod 'GooglePlacePicker', '= 2.0.1'
    pod 'GooglePlaces', '= 2.0.1'
    pod 'GoogleMaps', '= 2.0.1'
end

target 'exampleTests' do

end

